dist: trusty
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libglm-dev
    - graphviz
    - libxcb-dri3-0 
    - libxcb-present0
    - libpciaccess0
    - cmake
    - libpng-dev
    - libxcb-dri3-dev
    - libx11-dev
    - libmirclient-dev
    - libwayland-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxi-dev
install:
  - wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz
  - tar xvf cmake-3.8.2-Linux-x86_64.tar.gz
  - export CUSTOM_CMAKE=$PWD/cmake-3.8.2-Linux-x86_64/bin/cmake
  - wget https://vulkan.lunarg.com/sdk/download/1.0.61.1/linux/vulkansdk-linux-x86_64-1.0.61.1.run
  - chmod +x vulkansdk-linux-x86_64-1.0.61.1.run
  - ./vulkansdk-linux-x86_64-1.0.61.1.run
  - source VulkanSDK/1.0.61.1/setup-env.sh
script:
  - mkdir build
  - cd build
  - $CUSTOM_CMAKE ..
  - $CUSTOM_CMAKE --build .

