image: Visual Studio 2017

version: 0.1.0+{build}

install:
  - appveyor DownloadFile https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.0.61.1/windows/VulkanSDK-1.0.61.1-Installer.exe
  - VulkanSDK-1.0.61.1-Installer.exe /S
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 Win64"
  - cmake --build .
